// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/calculate_packs": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Packs"
                ],
                "summary": "Calculate packs",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.OrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.PacksNeeded"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.OrderRequest": {
            "type": "object",
            "properties": {
                "order_quantity": {
                    "type": "integer"
                }
            }
        },
        "model.PackDetails": {
            "type": "object",
            "properties": {
                "pack_size": {
                    "type": "integer"
                },
                "packs_count": {
                    "type": "integer"
                }
            }
        },
        "model.PacksNeeded": {
            "type": "object",
            "properties": {
                "order_quantity": {
                    "type": "integer"
                },
                "packs_needed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PackDetails"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
