definitions:
  model.OrderRequest:
    properties:
      order_quantity:
        type: integer
    type: object
  model.PackDetails:
    properties:
      pack_size:
        type: integer
      packs_count:
        type: integer
    type: object
  model.PacksNeeded:
    properties:
      order_quantity:
        type: integer
      packs_needed:
        items:
          $ref: '#/definitions/model.PackDetails'
        type: array
    type: object
info:
  contact: {}
paths:
  /api/v1/calculate_packs:
    post:
      consumes:
      - application/json
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.OrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PacksNeeded'
      summary: Calculate packs
      tags:
      - Packs
swagger: "2.0"
